name: ClockIn

on:
  push:
    branches: 
      - master
  watch:
    types: started
  schedule:
    - cron: 0 */12 * * *

jobs:
  ClockIn:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install python3
        run: |
          sudo -E apt-get -yqq update
          sudo -E apt-get -yqq install python3
      - name: Clock In
        env:
          ACCOUNT: ${{ secrets.ACCOUNT }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          python3 clock-in.py ${ACCOUNT} ${PASSWORD}
      - name: Get Date
        run: echo "REPORT_DATE=$(TZ=':Asia/Shanghai' date '+%Y-%m-%d %T')" >> $GITHUB_ENV
      - name: Send Email
        uses: actions/checkout@master
        with:
          server_address: smtp.163.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: ZJU clock in result. (${{env.REPORT_DATE}})
          body: file://email.txt
          to: 1836205414@qq.com
          from: GitHub Actions
          content_type: text/html
